### ISSUE TITLE
Naming Conflicts with Region Goal Tracker & Goal Tracker plugins

### ISSUE THREAD

**Issue by Marstead** [slaytostay/region-locker#33]
There's a Plugin on the hub called "Goal Tracker" (https://runelite.net/plugin-hub/show/goal-tracker) which presently has a bunch of naming conflicts with Region Goal Tracker. The main issue preventing both plugins from being **installed** simultaneously was fixed here https://github.com/slaytostay/region-locker/issues/22 but there is an enduring issue where both plugins cannot be turned on at the same time. This seems to be an internal issue with the way Region Goal Tracker settings are named in settings.properties (They still say "Goal Tracker" instead of "Region Goal Tracker").

To reproduce the issue, install both Region Locker and Goal Tracker and add some settings to both plugins. Then try turning them both on at once. Only one plugin will activate at once.

To fix this, all internal settings associated with Region Goal Tracker should be relabeled to "Region Goal Tracker" instead of just "Goal Tracker".

**Comment by aHooder** [comment]
Not having used these plugins before, I don't know what the best course of action would be. The issue seems to be that both of these plugins use the same config group key. If we fix this on our end by changing this key, that will reset any data that's tracked by that key, unless we write some code to port the settings over. What do you think might be the best approach here?

**Comment by aHooder** [comment]
It looks like Region Goal Tracker saves its goals to `goaltracker.goals`, while the other Goal Tracker saves its data to `goaltracker.goalTrackerData`. It seems like none of the config keys happen to overlap, so that's good at least. I could probably change Region Locker's goal tracker group key to something else, and have it auto load the old config key if it can't find any data from the new key.

Do you think people will be alright with all of the settings in the Region Goal Tracker config panel were reset? (other than saved goals)

**Comment by Marstead** [comment]
> Do you think people will be alright with all of the settings in the Region Goal Tracker config panel were reset? (other than saved goals)

I'd have to look at the plugin again to remind myself what is in those settings since we can't see it in RL now, but as long as the actual saved goals aren't being wiped it should not be a problem I think. If we're just talking about the shortlist of checkbox settings those should be easy for most people to replace. The goals represent a lot of manual work though.

**Comment by aHooder** [comment]
Here's a screenshot of the current settings panel: 
![image](https://user-images.githubusercontent.com/831317/226112997-0b25f3bb-6fda-4b56-b2b6-d6d01bc5f2bb.png)

**Comment by Marstead** [comment]
Thanks! Yeah those are all trivial to set back up, I would say if those get wiped it won't be a big deal.

**Comment by aHooder** [comment]
Fixed in d17cee41cfccadaafdb45135a19391a8cce09c81

**Comment by aHooder** [comment]
Nah, this set of changes was unfortunately not included in the first update. I will hopefully get around to submitting this next batch of fixes in not too long.

**Comment by Marstead** [comment]
Got it thank you!
